ODDS_API_HOST = 'https://api.the-odds-api.com'

ODDS_FORMAT = 'decimal'

DATE_FORMAT = 'iso'

REGIONS_LIST = [
    'us',
]

SPORTS_LIST = [
    'americanfootball_nfl',
    'americanfootball_ncaaf',
    'baseball_mlb',     
    'basketball_nba',
    'basketball_ncaab',
    'basketball_wnba',
    'icehockey_nfl',
]

BETTING_MARKETS = [
    'h2h',
    'spreads',
    'totals',
    'alternate_spreads',
    'alternate_totals', 
    'team_totals'
]

GAME_PROPS = [
    'h2h_q1',
    'h2h_q2',
    'h2h_q3',
    'h2h_q4',
    'h2h_p1',
    'h2h_p2',
    'h2h_p3',
    'h2h_1st_1_innings',
    'h2h_1st_3_innings',
    'h2h_1st_5_innings',
    'h2h_1st_7_innings',
    'h2h_3_way_1st_1_innings',
    'h2h_3_way_1st_3_innings',
    'h2h_3_way_1st_5_innings',
    'h2h_3_way_1st_7_innings',
    'spreads_q1',
    'spreads_q2',
    'spreads_q3',
    'spreads_q4',
    'spreads_p1',
    'spreads_p2',
    'spreads_p3',
    'spreads_1st_1_innings',
    'spreads_1st_3_innings',
    'spreads_1st_5_innings',
    'spreads_1st_7_innings',
    'alternate_spreads_1st_1_innings',
    'alternate_spreads_1st_3_innings',
    'alternate_spreads_1st_5_innings',
    'alternate_spreads_1st_7_innings',
    'alternate_spreads_q1',
    'alternate_spreads_h1',
    'totals_q1',
    'totals_q2',
    'totals_q3',
    'totals_q4',
    'totals_h1',
    'totals_h2',
    'totals_p1',
    'totals_p2',
    'totals_p3',
    'totals_1st_1_innings',
    'totals_1st_3_innings',
    'totals_1st_5_innings',
    'totals_1st_7_innings',
    'alternate_totals_1st_1_innings',
    'alternate_totals_1st_3_innings',
    'alternate_totals_1st_5_innings',
    'alternate_totals_1st_7_innings',
    'alternate_totals_q1',
    'alternate_totals_h1',
    'team_totals_h1',
    'team_totals_h2',
    'team_totals_q1',
    'team_totals_q2',
    'team_totals_q3',
    'team_totals_q4',
    'alternate_team_totals_h1',
    'alternate_team_totals_h2',
]

PLAYER_PROPS = {
    "americanfootball": {
        "leagues":['nfl', 'ncaaf'],
        "regular_props": [
            "player_assists",
            "player_field_goals",
            "player_kicking_points",
            "player_pass_attempts",
            "player_pass_completions",
            "player_pass_interceptions",
            "player_pass_longest_completion",
            "player_pass_rush_reception_tds",
            "player_pass_rush_reception_yds",
            "player_pass_tds",
            "player_pass_yds",
            "player_pats",
            "player_receptions",
            "player_rush_attempts",
            "player_rush_longest",
            "player_rush_reception_tds",
            "player_rush_reception_yds",
            "player_rush_yds",
            "player_sacks",
            "player_solo_tackles",
            "player_tackles_assists",
            "player_tds_over",
            "player_1st_td",
            "player_anytime_td",
            "player_last_td",
        ],
        "alternate_props": [
            "player_assists_alternate",
            "player_field_goals_alternate",
            "player_kicking_points_alternate",
            "player_pass_attempts_alternate",
            "player_pass_completions_alternate",
            "player_pass_interceptions_alternate",
            "player_pass_longest_completion_alternate",
            "player_pass_rush_reception_tds_alternate",
            "player_pass_rush_reception_yds_alternate",
            "player_pass_tds_alternate",
            "player_pass_yds_alternate",
            "player_pats_alternate",
            "player_receptions_alternate",
            "player_reception_longest_alternate",
            "player_reception_yds_alternate",
            "player_rush_attempts_alternate",
            "player_rush_longest_alternate",
            "player_rush_reception_tds_alternate",
            "player_rush_reception_yds_alternate",
            "player_rush_yds_alternate",
            "player_sacks_alternate",
            "player_solo_tackles_alternate",
            "player_tackles_assists_alternate",
        ]
    },
    "basketball": {
        "leagues":['nba', 'wnba', 'ncaab'],
        "regular_props": [
            "player_points",
            "player_rebounds",
            "player_assists",
            "player_threes",
            "player_blocks",
            "player_steals",
            "player_blocks_steals",
            "player_turnovers",
            "player_points_rebounds_assists",
            "player_points_rebounds",
            "player_points_assists",
            "player_rebounds_assists",
            "player_first_basket",
            "player_double_double",
            "player_triple_double",
        ],
        "alternate_props": [
            "player_points_alternate",
            "player_rebounds_alternate",
            "player_assists_alternate",
            "player_blocks_alternate",
            "player_steals_alternate",
            "player_threes_alternate",
            "player_points_assists_alternate",
            "player_points_rebounds_alternate",
            "player_rebounds_assists_alternate",
            "player_points_rebounds_assists_alternate",
        ]
    },
    "baseball": {
        "leagues": ['mlb'],
        "regular_props": [
            "batter_home_runs",
            "batter_first_home_run",
            "batter_hits",
            "batter_total_bases",
            "batter_rbis",
            "batter_runs_scored",
            "batter_hits_runs_rbis",
            "batter_singles",
            "batter_doubles",
            "batter_triples",
            "batter_walks",
            "batter_strikeouts",
            "batter_stolen_bases",
            "pitcher_strikeouts",
            "pitcher_record_a_win",
            "pitcher_hits_allowed",
            "pitcher_walks",
            "pitcher_earned_runs",
            "pitcher_outs",
            "pitcher_hits",
        ],
        "alternate_props": [
            "batter_total_bases_alternate",
            "batter_home_runs_alternate",
            "batter_hits_alternate",
            "batter_rbis_alternate",
            "pitcher_hits_allowed_alternate",
            "pitcher_walks_alternate",
            "pitcher_strikeouts_alternate",
        ],
    },
    "icehockey": {
        "leagues": ['nhl'],
        "regular_props": [
            "player_points",
            "player_power_play_points",
            "player_assists",
            "player_blocked_on_shots",
            "player_shots_on_goal",
            "player_goals",
            "player_total_saves",
            "player_goal_scorer_first",
            "player_goal_scorer_last",
            "player_goal_scorer_anytime",
        ],
        "alternate_props": [
            "player_points_alternate",
            "player_power_play_points_alternate",
            "player_assists_alternate",
            "player_blocked_on_shots_alternate",
            "player_shots_on_goal_alternate",
            "player_goals_alternate",
            "player_total_saves_alternate",
        ],
    }
}